export const cafesJson = [{
  _id: '1',
  cuisines: ['European', 'Galician', 'Jewish', 'Polish', 'Ukrainian', 'Vegetarian'],
  features: ['live music', 'movie screenings', 'pet-friendly', 'summer terrace', 'Wi-Fi'],
  categories: ['luxury restaurant'],
  bookings: [{
    date: '2017-10-07',
    tables: [{
      userId: '59cf80eb2debdcdd4f659abb',
      time: '17:00',
      people: 8,
      tableType: 4,
      tableAmount: 2
    }, {
      userId: '79cf80eb2debdcdd4f659abe',
      time: '21:00',
      people: 7,
      tableType: 2,
      tableAmount: 4
    }]
  }],
  tables: { tableType2: 3, tableType4: 4 },
  location: { lat: 49.8422154, lng: 24.0299315 },
  name: 'Baczewski Restaurant',
  rating: 4.6,
  address: '8 Shevska Str., Lviv, Ukraine',
  phones: ['+38 (098) 224-44-44', '+38 (032) 235-71-81'],
  web: 'http://kumpelgroup.com/restaurants/baczewski',
  logoImg: 'assets/img/logo/1.jpg',
  profileImg: 'assets/img/profile/1.jpg'
},
{
  _id: '2',
  cuisines: ['European', 'Italian', 'Ukrainian', 'Vegetarian'],
  features: ['bicycle parking', 'live music', 'movie screenings', 'summer terrace', 'Wi-Fi'],
  categories: ['pub'],
  bookings: [{
    date: '2017-10-08',
    tables: [{
      userId: '59cf80eb2debdcdd4f659abb',
      time: '17:00',
      people: 7,
      tableType: 4,
      tableAmount: 2
    }, {
      userId: '79cf80eb2debdcdd4f659abe',
      time: '21:00',
      people: 5,
      tableType: 2,
      tableAmount: 3
    }]
  }],
  tables: { tableType2: 3, tableType4: 2 },
  location: { lat: 49.8406424, lng: 24.0259706 },
  name: 'Kryva Lypa',
  rating: 4.6,
  address: '8 Kryva Lypa lane, Lviv, Ukraine',
  phones: ['+38 (032) 255-31-00', '+38 (098) 094-81-01'],
  web: 'http://kryva-lypa.com',
  logoImg: 'assets/img/logo/2.jpg',
  profileImg: 'assets/img/profile/2.jpg'
},
{
  _id: '3',
  cuisines: ['Galician', 'Hungarian', 'Italian', 'Polish', 'Ukrainian'],
  features: ['live music', 'summer terrace', 'Wi-Fi'],
  categories: ['brewery', 'pub'],
  bookings: [{
    date: '2017-10-07',
    tables: [{
      userId: '59cf80eb2debdcdd4f659abb',
      time: '17:00',
      people: 9,
      tableType: 4,
      tableAmount: 3
    }, {
      userId: '79cf80eb2debdcdd4f659abe',
      time: '21:00',
      people: 12,
      tableType: 2,
      tableAmount: 6
    }]
  }],
  tables: { tableType2: 12, tableType4: 9 },
  location: { lat: 49.8466037, lng: 24.0258222 },
  name: 'Kumpel',
  rating: 4.6,
  address: '2B Chornovola Ave., Lviv, Ukraine',
  phones: ['+38 (032) 229-51-77', '+38 (068) 998-99-95'],
  web: 'http://kumpelgroup.com/restaurants/new-kumpel',
  logoImg: 'assets/img/logo/3.jpg',
  profileImg: 'assets/img/profile/3.jpg'
},
{
  cuisines: ['European', 'Ukrainian'],
  features: ['museum', 'roof terrace', 'summer terrace', 'Wi-Fi'],
  categories: ['pub', 'thematic restaurant'],
  bookings: [{
    date: '2017-10-08',
    tables: [{
      userId: '59cf80eb2debdcdd4f659abb',
      time: '17:00',
      people: 7,
      tableType: 4,
      tableAmount: 2
    }, {
      userId: '79cf80eb2debdcdd4f659abe',
      time: '21:00',
      people: 5,
      tableType: 2,
      tableAmount: 3
    }]
  }],
  tables: { tableType2: 3, tableType4: 3 },
  location: { lat: 49.8431720, lng: 24.0316031 },
  name: 'Gasova Lampa',
  rating: 4.6,
  address: '20 Virmenska Str., Lviv, Ukraine',
  phones: ['+38 (050) 430-14-51'],
  web: 'http://www.fest.lviv.ua/uk/restaurants/gasovalampa',
  logoImg: 'assets/img/logo/4.jpg',
  profileImg: 'assets/img/profile/4.jpg'
},
{
  cuisines: ['Polish', 'Ukrainian'],
  features: ['summer terrace', 'Wi-Fi'],
  categories: ['pub'],
  bookings: [{
    date: '2017-10-07',
    tables: [{
      userId: '59cf80eb2debdcdd4f659abb',
      time: '17:00',
      people: 7,
      tableType: 4,
      tableAmount: 2
    }, {
      userId: '79cf80eb2debdcdd4f659abe',
      time: '21:00',
      people: 5,
      tableType: 2,
      tableAmount: 3
    }]
  }],
  tables: { tableType2: 8, tableType4: 6 },
  location: { lat: 49.8438986, lng: 24.0302972 },
  name: 'White Lion',
  rating: 4.7,
  address: '15 Lesya Ukrainka Str., Lviv, Ukraine',
  phones: ['+38 (032) 235-46-25', '+38 (067) 675-51-23'],
  web: 'http://www.white-lion.com.ua',
  logoImg: 'assets/img/logo/5.jpg',
  profileImg: 'assets/img/profile/5.jpg'
},
{
  cuisines: ['European', 'Ukrainian', 'Vegetarian'],
  features: ['live music', 'summer terrace', 'Wi-Fi'],
  categories: ['brewery', 'pub'],
  bookings: [{
    date: '2017-10-08',
    tables: [{
      userId: '59cf80eb2debdcdd4f659abb',
      time: '17:00',
      people: 7,
      tableType: 4,
      tableAmount: 2
    }, {
      userId: '79cf80eb2debdcdd4f659abe',
      time: '21:00',
      people: 5,
      tableType: 2,
      tableAmount: 3
    }]
  }],
  tables: { tableType2: 3, tableType4: 3 },
  location: { lat: 49.8421389, lng: 24.0304114 },
  name: 'PRAVDA Beer Theater',
  rating: 4.5,
  address: '32 Rynok Sqr., Lviv, Ukraine',
  phones: ['+38 (067) 310-83-23', '+38 (050) 374-49-86'],
  web: 'http://www.pravda.beer',
  logoImg: 'assets/img/logo/6.jpg',
  profileImg: 'assets/img/profile/6.jpg'
},
{
  cuisines: ['European', 'Galician', 'Hungarian', 'Ukrainian'],
  features: ['billiards', 'live music', 'summer terrace', 'Wi-Fi'],
  categories: ['coffee house'],
  bookings: [{
    date: '2017-10-07',
    tables: [{
      userId: '59cf80eb2debdcdd4f659abb',
      time: '17:00',
      people: 7,
      tableType: 4,
      tableAmount: 2
    }, {
      userId: '79cf80eb2debdcdd4f659abe',
      time: '21:00',
      people: 5,
      tableType: 2,
      tableAmount: 3
    }]
  }],
  tables: { tableType2: 4, tableType4: 2 },
  location: { lat: 49.8409210, lng: 24.0287660 },
  name: 'Vienna Coffee House',
  rating: 4.8,
  address: '12 Svobody Ave., Lviv, Ukraine',
  phones: ['+38 (032) 235-87-21', '+38 (050) 391-22-40'],
  web: 'http://www.wienkaffe.com.ua',
  logoImg: 'assets/img/logo/7.jpg',
  profileImg: 'assets/img/profile/7.jpg'
},
{
  cuisines: ['European', 'Galician'],
  features: ['non-smoking area', 'summer terrace', 'Wi-Fi'],
  categories: ['coffee house'],
  bookings: [{
    date: '2017-10-08',
    tables: [{
      userId: '59cf80eb2debdcdd4f659abb',
      time: '17:00',
      people: 14,
      tableType: 4,
      tableAmount: 4
    }, {
      userId: '79cf80eb2debdcdd4f659abe',
      time: '21:00',
      people: 9,
      tableType: 2,
      tableAmount: 5
    }]
  }],
  tables: { tableType2: 18, tableType4: 11 },
  location: { lat: 49.8416410, lng: 24.0300720 },
  name: 'Na Bambetli',
  rating: 4.6,
  address: '29 Rynok Sqr., Lviv, Ukraine',
  phones: ['+38 (032) 235-45-44'],
  web: 'http://nabambetli.com',
  logoImg: 'assets/img/logo/8.jpg',
  profileImg: 'assets/img/profile/8.jpg'
},
{
  cuisines: ['European'],
  features: ['summer terrace', 'Wi-Fi'],
  categories: ['coffee house'],
  bookings: [{
    date: '2017-10-07',
    tables: [{
      userId: '59cf80eb2debdcdd4f659abb',
      time: '17:00',
      people: 9,
      tableType: 4,
      tableAmount: 2
    }, {
      userId: '79cf80eb2debdcdd4f659abe',
      time: '21:00',
      people: 5,
      tableType: 2,
      tableAmount: 3
    }]
  }],
  tables: { tableType2: 8, tableType4: 6 },
  location: { lat: 49.8434696, lng: 24.0297379 },
  name: 'Brown Tea & Coffee Shop',
  rating: 4.3,
  address: '1 Kornyakta Str., Lviv, Ukraine',
  phones: ['+38 (067) 737-88-98'],
  web: 'http://brown.com.ua',
  logoImg: 'assets/img/logo/9.jpg',
  profileImg: 'assets/img/profile/9.jpg'
},
{
  cuisines: ['European', 'Ukrainian'],
  features: ['aphrodisiacs', 'show program', 'Wi-Fi'],
  categories: ['pub', 'thematic restaurant'],
  bookings: [{
    date: '2017-10-08',
    tables: [{
      userId: '59cf80eb2debdcdd4f659abb',
      time: '17:00',
      people: 7,
      tableType: 4,
      tableAmount: 2
    }, {
      userId: '79cf80eb2debdcdd4f659abe',
      time: '21:00',
      people: 5,
      tableType: 2,
      tableAmount: 3
    }]
  }],
  tables: { tableType2: 8, tableType4: 6 },
  location: { lat: 49.8410608, lng: 24.0331564 },
  name: 'Mazoh-Cafe',
  rating: 4.4,
  address: '7 Serbska Str., Lviv, Ukraine',
  phones: ['+38 (032) 272-18-72', '+38 (050) 371-04-40'],
  web: 'https://www.facebook.com/MasochCafe',
  logoImg: 'assets/img/logo/10.jpg',
  profileImg: 'assets/img/profile/10.jpg'
},
{
  cuisines: ['Galician', 'Ukrainian'],
  features: ['24h', 'shooting gallery', 'show program', 'Wi-Fi'],
  categories: ['pub', 'thematic restaurant'],
  bookings: [{
    date: '2017-10-07',
    tables: [{
      userId: '59cf80eb2debdcdd4f659abb',
      time: '17:00',
      people: 3,
      tableType: 4,
      tableAmount: 1
    }, {
      userId: '79cf80eb2debdcdd4f659abe',
      time: '21:00',
      people: 5,
      tableType: 2,
      tableAmount: 3
    }]
  }],
  tables: { tableType2: 4, tableType4: 3 },
  location: { lat: 49.8414464, lng: 24.0321777 },
  name: 'Kryivka',
  rating: 4.5,
  address: '14 Rynok Sqr., Lviv, Ukraine',
  phones: ['+38 (032) 254-61-19', '+38 (050) 430-63-54'],
  web: 'https://www.facebook.com/kryjivkalviv',
  logoImg: 'assets/img/logo/11.jpg',
  profileImg: 'assets/img/profile/11.jpg'
},
{
  cuisines: ['Author\'s', 'European', 'Polish', 'Ukrainian', 'Vegetarian'],
  features: ['bicycle parking', 'live music', 'summer terrace', 'Wi-Fi'],
  categories: ['luxury restaurant'],
  bookings: [{
    date: '2017-10-08',
    tables: [{
      userId: '59cf80eb2debdcdd4f659abb',
      time: '17:00',
      people: 7,
      tableType: 4,
      tableAmount: 2
    }, {
      userId: '79cf80eb2debdcdd4f659abe',
      time: '21:00',
      people: 5,
      tableType: 2,
      tableAmount: 3
    }]
  }],
  tables: { tableType2: 6, tableType4: 6 },
  location: { lat: 49.8418096, lng: 24.0311066 },
  name: 'Ratusha-Cafe',
  rating: 4.8,
  address: '1 Rynok Sqr., Lviv, Ukraine',
  phones: ['+38 (032) 297-55-65', '+38 (097) 997-55-65'],
  web: 'http://caferatusha.lviv.ua',
  logoImg: 'assets/img/logo/12.jpg',
  profileImg: 'assets/img/profile/12.jpg'
},
{
  cuisines: ['European', 'Ukrainian', 'Vegetarian'],
  features: ['roof terrace', 'show program', 'sports broadcast', 'Wi-Fi'],
  categories: ['pub', 'thematic restaurant'],
  bookings: [{
    date: '2017-10-07',
    tables: [{
      userId: '59cf80eb2debdcdd4f659abb',
      time: '17:00',
      people: 9,
      tableType: 4,
      tableAmount: 2
    }, {
      userId: '79cf80eb2debdcdd4f659abe',
      time: '21:00',
      people: 6,
      tableType: 2,
      tableAmount: 3
    }]
  }],
  tables: { tableType2: 5, tableType4: 5 },
  location: { lat:  49.8410681, lng: 24.0344760 },
  name: 'House of Legends',
  rating: 4.5,
  address: '48 Staroevreiska Str., Lviv, Ukraine',
  phones: ['+38 (050) 430-29-24', '+38 (067) 670-38-28'],
  web: 'https://www.facebook.com/dimlegend',
  logoImg: 'assets/img/logo/13.jpg',
  profileImg: 'assets/img/profile/13.jpg'
},
{
  cuisines: ['American', 'European', 'French', 'Italian'],
  features: ['live music', 'summer terrace', 'Wi-Fi'],
  categories: ['luxury restaurant', 'thematic restaurant'],
  bookings: [{
    date: '2017-10-08',
    tables: [{
      userId: '59cf80eb2debdcdd4f659abb',
      time: '17:00',
      people: 7,
      tableType: 4,
      tableAmount: 2
    }, {
      userId: '79cf80eb2debdcdd4f659abe',
      time: '21:00',
      people: 11,
      tableType: 2,
      tableAmount: 6
    }]
  }],
  tables: { tableType2: 6, tableType4: 4 },
  location: { lat: 49.8413707, lng: 24.0322059 },
  name: 'Masonic lodge',
  rating: 4.7,
  address: '14 Rynok Str., Lviv, Ukraine',
  phones: ['+38 (050) 430-87-83'],
  web: 'https://www.facebook.com/NaidorozhchaRestoracijaGalychyny',
  logoImg: 'assets/img/logo/14.jpg',
  profileImg: 'assets/img/profile/14.jpg'
},
{
  cuisines: ['European', 'Italian', 'Ukrainian', 'Vegetarian'],
  features: ['live music', 'museum', 'parking', 'summer terrace', 'Wi-Fi'],
  categories: ['art cafe', 'pub', 'thematic restaurant'],
  bookings: [],
  tables: { tableType2: 6, tableType4: 4 },
  location: { lat: 49.8439466, lng: 24.0265666 },
  name: 'Left Bank',
  rating: 4.3,
  address: '28 Svobody Ave., Lviv, Ukraine',
  phones: ['+38 (050) 430-07-52', '+38 (050) 430-53-85'],
  web: 'http://www.fest.lviv.ua/uk/restaurants/livyjbereh',
  logoImg: 'assets/img/logo/15.jpg',
  profileImg: 'assets/img/profile/15.jpg'
},
{
  cuisines: ['European', 'Ukrainian'],
  features: ['kid-friendly', 'parking', 'summer terrace', 'Wi-Fi'],
  categories: ['barbecue', 'grill', 'pub', 'thematic restaurant'],
  bookings: [],
  tables: { tableType2: 6, tableType4: 4 },
  location: { lat: 49.8403901, lng: 24.0357132 },
  name: 'The First Lviv Grill Restaurant of Meat and Justice',
  rating: 4.6,
  address: '20 Valova Str., Lviv, Ukraine',
  phones: ['+38 (050) 430-28-26', '+38 (067) 670-25-10'],
  web: 'http://www.fest.lviv.ua/uk/restaurants/meatandjustice',
  logoImg: 'assets/img/logo/16.jpg',
  profileImg: 'assets/img/profile/16.jpg'
},
{
  cuisines: ['European', 'Vegetarian'],
  features: ['live music', 'movie screenings', 'parking', 'Wi-Fi'],
  categories: ['alcohol-free', 'art cafe', 'healthy restaurant'],
  bookings: [],
  tables: { tableType2: 6, tableType4: 4 },
  location: { lat: 49.8399541, lng: 24.0309967 },
  name: 'Green',
  rating: 4.5,
  address: '5 Brativ Rohatyntsiv Str., Lviv, Ukraine',
  phones: ['+38 (097) 773-77-00'],
  web: 'https://www.facebook.com/greenlviv',
  logoImg: 'assets/img/logo/17.jpg',
  profileImg: 'assets/img/profile/17.jpg'
},
{
  cuisines: ['Austrian', 'European', 'German', 'Ukrainian', 'Vegetarian'],
  features: ['summer terrace', 'Wi-Fi'],
  categories: ['coffee house'],
  bookings: [],
  tables: { tableType2: 6, tableType4: 4 },
  location: { lat: 49.8422128, lng: 24.0300362 },
  name: 'Strudel House',
  rating: 4.6,
  address: '6 Shevska Str., Lviv, Ukraine',
  phones: ['+38 (032) 294-82-06'],
  web: 'http://kumpelgroup.com/restaurants/strudel-haus',
  logoImg: 'assets/img/logo/18.jpg',
  profileImg: 'assets/img/profile/18.jpg'
},
{
  cuisines: ['Armenian', 'Caucasian', 'European', 'Ukrainian', 'Vegetarian'],
  features: ['live music', 'parking', 'summer terrace', 'Wi-Fi'],
  categories: ['barbecue', 'coffee house', 'kebab house', 'pizza'],
  bookings: [],
  tables: { tableType2: 6, tableType4: 4 },
  location: { lat: 49.8367668, lng: 24.0107394 },
  name: 'Yerevan',
  rating: 4.3,
  address: '8 Mytropolyta Andreya Str., Lviv, Ukraine',
  phones: ['+38 (032) 237-77-21', '+38 (098) 174 24 00'],
  web: 'https://www.facebook.com/pg/restoran.erevan.lviv',
  logoImg: 'assets/img/logo/19.jpg',
  profileImg: 'assets/img/profile/19.jpg'
},
{
  cuisines: ['Author\'s', 'European'],
  features: ['alcoves', 'live music', 'summer terrace', 'Wi-Fi'],
  categories: ['barbecue', 'thematic restaurant'],
  bookings: [],
  tables: { tableType2: 6, tableType4: 4 },
  location: { lat: 49.8436730, lng: 24.0316159 },
  name: 'Tlustyi Husak',
  rating: 4.5,
  address: '9 Drukarska Str., Lviv, Ukraine',
  phones: ['+38 (067) 238-24-94'],
  web: 'http://gusak-restaurant.lviv.ua/en',
  logoImg: 'assets/img/logo/20.jpg',
  profileImg: 'assets/img/profile/20.jpg'
},
{
  cuisines: ['European', 'Galician', 'Ukrainian', 'Vegetarian'],
  features: ['parking', 'summer terrace', 'Wi-Fi'],
  categories: ['coffee house'],
  bookings: [],
  tables: { tableType2: 6, tableType4: 4 },
  location: { lat: 49.8405917, lng: 24.0334551 },
  name: 'Trapezna',
  rating: 4.6,
  address: '18A Valova Str., Lviv, Ukraine',
  phones: ['+38(032) 254-61-55'],
  web: 'http://idem.org.ua/projects/idea/trapezna',
  logoImg: 'assets/img/logo/21.jpg',
  profileImg: 'assets/img/profile/21.jpg'
},
{
  cuisines: ['Galician'],
  features: ['fishing', 'kid-friendly', 'live music', 'parking', 'summer terrace', 'wheelchair ramp', 'Wi-Fi'],
  categories: ['family restaurant'],
  bookings: [],
  tables: { tableType2: 6, tableType4: 4 },
  location: { lat: 49.7770584, lng: 24.0128842 },
  name: 'Hungry Nickolas',
  rating: 4.7,
  address: '352 Stryiska Str., Lviv, Ukraine',
  phones: ['+38 (098) 229-22-22'],
  web: 'http://kumpelgroup.com/restaurants/hungry-mukola',
  logoImg: 'assets/img/logo/22.jpg',
  profileImg: 'assets/img/profile/22.jpg'
},
{
  cuisines: ['Chinese', 'European', 'Japanese', 'Italian', 'Thai'],
  features: ['summer terrace', 'Wi-Fi'],
  categories: ['sushi', 'pizza'],
  bookings: [],
  tables: { tableType2: 6, tableType4: 4 },
  location: { lat: 49.8408163, lng: 24.0250633 },
  name: 'Red Pepper',
  rating: 4.6,
  address: '5 Sichovykh Striltsiv Str., Lviv, Ukraine',
  phones: ['+38 (068) 320-37-39'],
  web: 'http://redpepper.com.ua',
  logoImg: 'assets/img/logo/23.jpg',
  profileImg: 'assets/img/profile/23.jpg'
},
{
  cuisines: ['European', 'French', 'Italian', 'Ukrainian', 'Vegetarian'],
  features: ['kid-friendly', 'live music', 'parking', 'summer terrace', 'wheelchair ramp', 'Wi-Fi'],
  categories: ['barbecue', 'family restaurant', 'luxury restaurant'],
  bookings: [],
  tables: { tableType2: 6, tableType4: 4 },
  location: { lat: 49.8404510, lng: 24.0302762 },
  name: 'Amadeus',
  rating: 4.6,
  address: '7 Katedralna Sqr., Lviv, Ukraine',
  phones: ['+38 (032) 235-63-16'],
  web: 'https://www.facebook.com/pages/Amadeus/198929063461586',
  logoImg: 'assets/img/logo/24.jpg',
  profileImg: 'assets/img/profile/24.jpg'
},
{
  cuisines: ['Asian', 'Japanese', 'Vegetarian'],
  features: ['kid-friendly', 'summer terrace', 'Wi-Fi'],
  categories: ['sushi'],
  bookings: [],
  tables: { tableType2: 6, tableType4: 4 },
  location: { lat: 49.8496047, lng: 24.0213077 },
  name: 'Sushiya',
  rating: 4.5,
  address: '7B Pid Dubom Str., Lviv, Ukraine',
  phones: ['+38 (067) 238-24-94'],
  web: 'https://www.sushiya.ua',
  logoImg: 'assets/img/logo/25.jpg',
  profileImg: 'assets/img/profile/25.jpg'
},
{
  cuisines: ['European', 'Ukrainian', 'Vegetarian'],
  features: ['summer terrace', 'Wi-Fi'],
  categories: ['art cafe', 'family restaurant', 'healthy restaurant'],
  bookings: [],
  tables: { tableType2: 6, tableType4: 4 },
  location: { lat: 49.8427032, lng: 24.0246795 },
  name: 'Smakolyk',
  rating: 4.4,
  address: '5 Mykhalchuka Str., Lviv, Ukraine',
  phones: ['+38 (032) 245-22-84', '+38 (096) 647-38-83'],
  web: 'http://smakolyk.com',
  logoImg: 'assets/img/logo/26.jpg',
  profileImg: 'assets/img/profile/26.jpg'
},
{
  cuisines: ['Belgian', 'European', 'Vegetarian'],
  features: ['kid-friendly', 'summer terrace', 'Wi-Fi'],
  categories: ['coffee house', 'healthy restaurant'],
  bookings: [],
  tables: { tableType2: 6, tableType4: 4 },
  location: { lat: 49.8408980, lng: 24.0337847 },
  name: 'SOWA',
  rating: 4.5,
  address: '40 Staroevreiska Str., Lviv, Ukraine',
  phones: ['+38 (098) 634-90-46'],
  web: 'https://www.facebook.com/sowalviv',
  logoImg: 'assets/img/logo/27.jpg',
  profileImg: 'assets/img/profile/27.jpg'
},
{
  cuisines: ['Georgian'],
  features: ['parking', 'summer terrace', 'Wi-Fi'],
  categories: ['grill', 'kebab house'],
  bookings: [],
  tables: { tableType2: 6, tableType4: 4 },
  location: { lat: 49.8405751, lng: 24.0268787 },
  name: 'Hinkalnia',
  rating: 4.3,
  address: '1 Kryva Lypa lane, Lviv, Ukraine',
  phones: ['+38 (066) 600-26-55'],
  web: 'http://www.hinkalnya.com.ua/',
  logoImg: 'assets/img/logo/28.jpg',
  profileImg: 'assets/img/profile/28.jpg'
},
{
  cuisines: ['Georgian'],
  features: ['parking', 'summer terrace', 'Wi-Fi'],
  categories: ['grill', 'kebab house'],
  bookings: [],
  tables: { tableType2: 6, tableType4: 4 },
  location: { lat: 49.8496863, lng: 24.0213017 },
  name: 'Hinkalnia',
  rating: 4.3,
  address: '7 Pid Dubom Str., Lviv, Ukraine',
  phones: ['+38 (097) 715-71-57'],
  web: 'http://www.hinkalnya.com.ua/',
  logoImg: 'assets/img/logo/28.jpg',
  profileImg: 'assets/img/profile/29.jpg'
},
{
  cuisines: ['Georgian'],
  features: ['parking', 'summer terrace', 'Wi-Fi'],
  categories: ['grill', 'kebab house'],
  bookings: [],
  tables: { tableType2: 6, tableType4: 4 },
  location: { lat: 49.8421921, lng: 24.0334754 },
  name: 'Hinkalnia',
  rating: 4.3,
  address: '14 Fedorova Str., Lviv, Ukraine',
  phones: ['+38 (032) 236-71-01'],
  web: 'http://www.hinkalnya.com.ua/',
  logoImg: 'assets/img/logo/28.jpg',
  profileImg: 'assets/img/profile/30.jpg'
},
{
  cuisines: ['Georgian'],
  features: ['parking', 'summer terrace', 'Wi-Fi'],
  categories: ['grill', 'kebab house'],
  bookings: [],
  tables: { tableType2: 6, tableType4: 4 },
  location: { lat: 49.8042869, lng: 23.9875963 },
  name: 'Hinkalnia',
  rating: 4.3,
  address: '51 Naukova Str., Lviv, Ukraine',
  phones: ['+38 (068) 503 23 36'],
  web: 'http://www.hinkalnya.com.ua',
  logoImg: 'assets/img/logo/28.jpg',
  profileImg: 'assets/img/profile/31.jpg'
},
{
  cuisines: ['Georgian'],
  features: ['parking', 'summer terrace', 'Wi-Fi'],
  categories: ['grill', 'kebab house'],
  bookings: [],
  tables: { tableType2: 6, tableType4: 4 },
  location: { lat: 49.8626130, lng: 24.0172150 },
  name: 'Hinkalnia',
  rating: 4.3,
  address: '93 Chornovola Ave., Lviv, Ukraine',
  phones: ['+38 (067) 676-42-93', '+38 (066) 822-28-70'],
  web: 'http://www.hinkalnya.com.ua',
  logoImg: 'assets/img/logo/28.jpg',
  profileImg: 'assets/img/profile/32.jpg'
},
{
  cuisines: ['Asian', 'Japanese', 'Vegetarian'],
  features: ['kid-friendly', 'Wi-Fi'],
  categories: ['sushi'],
  bookings: [],
  tables: { tableType2: 6, tableType4: 4 },
  location: { lat: 49.8400352, lng: 24.0293592 },
  name: 'Yappi Sushi Island',
  rating: 4.1,
  address: '6/8 Svobody Ave., Lviv, Ukraine',
  phones: ['+38 (032) 235-69-72', '+38 (067) 674-45-15'],
  web: 'https://yappi.lviv.ua/',
  logoImg: 'assets/img/logo/33.jpg',
  profileImg: 'assets/img/profile/33.jpg'
},
{
  cuisines: ['European'],
  features: ['summer terrace', 'Wi-Fi'],
  categories: ['coffee house'],
  bookings: [],
  tables: { tableType2: 6, tableType4: 4 },
  location: { lat: 49.8397125, lng: 24.0317261 },
  name: 'Kredens Cafe',
  rating: 4.5,
  address: '5 Valova Str., Lviv, Ukraine',
  phones: ['+38 (032) 235-56-36'],
  web: 'http://www.kredens.com.ua',
  logoImg: 'assets/img/logo/34.jpg',
  profileImg: 'assets/img/profile/34.jpg'
},
{
  cuisines: ['European'],
  features: ['summer terrace', 'Wi-Fi'],
  categories: ['coffee house'],
  bookings: [],
  tables: { tableType2: 6, tableType4: 4 },
  location: { lat: 49.8432146, lng: 24.0260653 },
  name: 'Kredens Cafe',
  rating: 4.5,
  address: '37 Svobody Ave., Lviv, Ukraine',
  phones: ['+38 (032) 272-85-34'],
  web: 'http://www.kredens.com.ua',
  logoImg: 'assets/img/logo/34.jpg',
  profileImg: 'assets/img/profile/35.jpg'
},
{
  cuisines: ['Italian'],
  features: ['parking', 'summer terrace', 'Wi-Fi'],
  categories: ['fast food', 'pizza'],
  bookings: [],
  tables: { tableType2: 6, tableType4: 4 },
  location: { lat: 49.8114522, lng: 23.9863372 },
  name: 'Chelentano',
  rating: 4.1,
  address: '123 Volodymyr Velykyi Str., Lviv, Ukraine',
  phones: ['+38 (032) 234-25-67', '+38 (096) 916-01-20'],
  web: 'http://egoisty.com/menu/pica-chelentano-lviv-v-velikogo-123-uk',
  logoImg: 'assets/img/logo/36.jpg',
  profileImg: 'assets/img/profile/36.jpg'
},
{
  cuisines: ['Italian'],
  features: ['non-smoking area', 'summer terrace', 'Wi-Fi'],
  categories: ['fast food', 'pizza'],
  bookings: [],
  tables: { tableType2: 6, tableType4: 4 },
  location: { lat: 49.8375100, lng: 24.0385071 },
  name: 'Leopoli Pizza on the Wood',
  rating: 4.4,
  address: '4 Tugan-Baranovsky Str., Lviv, Ukraine',
  phones: ['+38 (032) 276-60-69', '+38 (067) 438-91-93'],
  web: 'http://pizza-leopoli.lviv.ua',
  logoImg: 'assets/img/logo/37.jpg',
  profileImg: 'assets/img/profile/37.jpg'
},
{
  cuisines: ['Chinese', 'Japanese'],
  features: ['parking', 'summer terrace', 'Wi-Fi'],
  categories: ['fast food'],
  bookings: [],
  tables: { tableType2: 6, tableType4: 4 },
  location: { lat: 49.8336467, lng: 24.0329945 },
  name: 'Peking',
  rating: 4.3,
  address: '8 Hrushevsky Str., Lviv, Ukraine',
  phones: ['+38 (032) 276-60-69', '+38 (067) 438-91-93'],
  web: 'http://pekin.lviv.ua/uk/main',
  logoImg: 'assets/img/logo/38.jpg',
  profileImg: 'assets/img/profile/38.jpg'
},
{
  cuisines: ['Asian', 'Chinese', 'Thai'],
  features: ['parking', 'summer terrace', 'Wi-Fi'],
  categories: ['fast food'],
  bookings: [],
  tables: { tableType2: 6, tableType4: 4 },
  location: { lat: 49.8425603, lng: 24.0303748 },
  name: 'Tikithai',
  rating: 4.1,
  address: '4 Krakivska Str., Lviv, Ukraine',
  phones: ['+38 (098) 175-77-87'],
  web: 'http://tikithai.ua/',
  logoImg: 'assets/img/logo/39.jpg',
  profileImg: 'assets/img/profile/39.jpg'
},
{
  cuisines: ['Crimean', 'European'],
  features: ['Wi-Fi'],
  categories: ['alcohol-free', 'coffee house'],
  bookings: [],
  tables: { tableType2: 6, tableType4: 4 },
  location: { lat: 49.843661, lng: 24.0253499 },
  name: 'Krym',
  rating: 4.5,
  address: '1A Furmanska Str., Lviv, Ukraine',
  phones: ['+380 (98) 677-77-69'],
  web: 'http://krim-cafe.com.ua',
  logoImg: 'assets/img/logo/40.jpg',
  profileImg: 'assets/img/profile/40.jpg'
},
{
  cuisines: ['European', 'Ukrainian', 'Vegetarian'],
  features: ['kid-friendly', 'Wi-Fi'],
  categories: ['coffee house', 'fast food'],
  bookings: [],
  tables: { tableType2: 6, tableType4: 4 },
  location: { lat: 49.8402470, lng: 24.0237900 },
  name: 'Puzata Khata',
  rating: 4.4,
  address: '12 Sichovykh Striltsiv Str., Lviv, Ukraine',
  phones: ['+380 (32) 240-32-65'],
  web: 'http://www.puzatahata.com.ua',
  logoImg: 'assets/img/logo/41.jpg',
  profileImg: 'assets/img/profile/41.jpg'
},
{
  cuisines: ['European', 'Hungarian', 'Ukrainian'],
  features: ['barman show', 'kid-friendly', 'live music', 'parking', 'pet-friendly', 'summer terrace', 'sports broadcast', 'Wi-Fi'],
  categories: ['lounge bar'],
  bookings: [],
  tables: { tableType2: 6, tableType4: 4 },
  location: { lat: 49.8164495, lng: 24.0689993 },
  name: 'Three Oscars',
  rating: 4.2,
  address: '5A George Washington Str., Lviv, Ukraine',
  phones: ['+38 (032) 245-89-73', '+38 (050) 948-86-14'],
  web: 'http://trioskara.virtual.ua/ua',
  logoImg: 'assets/img/logo/42.jpg',
  profileImg: 'assets/img/profile/42.jpg'
},
{
  cuisines: ['Author\'s', 'European', 'Ukrainian', 'Vegetarian'],
  features: ['kid-friendly', 'live music', 'parking', 'sports broadcast', 'summer terrace', 'wheelchair ramp', 'Wi-Fi'],
  categories: ['barbecue', 'family restaurant', 'grill'],
  bookings: [],
  tables: { tableType2: 6, tableType4: 4 },
  location: { lat: 49.8213188, lng: 24.0201475 },
  name: 'Love & Lviv',
  rating: 4.6,
  address: '66 Stryiska Str., Lviv, Ukraine',
  phones: ['+38 (098) 715-88-51', '+38 (032) 241-96-05'],
  web: 'https://www.loveandlviv.com',
  logoImg: 'assets/img/logo/43.jpg',
  profileImg: 'assets/img/profile/43.jpg'
},
{
  cuisines: ['European', 'Italian', 'Mediterranean', 'Vegetarian'],
  features: ['kid-friendly', 'live music', 'parking', 'roof terrace', 'Wi-Fi'],
  categories: ['family restaurant'],
  bookings: [],
  tables: { tableType2: 6, tableType4: 4 },
  location: { lat: 49.8451244, lng: 24.0297548 },
  name: 'Terrazza',
  rating: 4.7,
  address: '3 Zvenyhorodska Str., Lviv, Ukraine',
  phones: ['+38 (098) 090-49-90', '+38 (093) 439-93-10'],
  web: 'http://terrazza.lviv.ua',
  logoImg: 'assets/img/logo/44.jpg',
  profileImg: 'assets/img/profile/44.jpg'
},
{
  cuisines: ['European'],
  features: ['museum', 'Wi-Fi'],
  categories: ['art cafe', 'coffee house'],
  bookings: [],
  tables: { tableType2: 6, tableType4: 4 },
  location: { lat: 49.8386822, lng: 24.0321676 },
  name: 'Fixage',
  rating: 4.5,
  address: '6 Kniazia Romana Str., Lviv, Ukraine',
  phones: ['+38 (063) 021-01-80', '+38 (098) 321-34-64'],
  web: 'https://www.facebook.com/fixagephotocaffe',
  logoImg: 'assets/img/logo/45.jpg',
  profileImg: 'assets/img/profile/45.jpg'
},
{
  cuisines: ['Italian'],
  features: ['kid-friendly', 'parking', 'summer terrace', 'Wi-Fi'],
  categories: ['pizza'],
  bookings: [],
  tables: { tableType2: 6, tableType4: 4 },
  location: { lat: 49.8372207, lng: 24.0347683 },
  name: 'Celentano Ristorante',
  rating: 4.6,
  address: '3 Shukhevych Str., Lviv, Ukraine',
  phones: ['+38 (032) 254-67-55'],
  web: 'https://www.facebook.com/chelentanoristoranteibis',
  logoImg: 'assets/img/logo/46.jpg',
  profileImg: 'assets/img/profile/46.jpg'
},
{
  cuisines: ['Asian', 'European', 'Italian', 'Ukrainian'],
  features: ['barman show', 'hookah', 'play station', 'summer terrace', 'Wi-Fi'],
  categories: ['lounge bar'],
  bookings: [],
  tables: { tableType2: 6, tableType4: 4 },
  location: { lat: 49.8395689, lng: 24.0316106 },
  name: 'Hashtag',
  rating: 4.4,
  address: '6 Valova Str., Lviv, Ukraine',
  phones: ['+38 (098) 922-52-09'],
  web: 'https://www.facebook.com/HashtagLoungeBar',
  logoImg: 'assets/img/logo/47.jpg',
  profileImg: 'assets/img/profile/47.jpg'
},
{
  cuisines: ['Asian', 'European', 'Italian', 'Ukrainian'],
  features: ['hookah', 'play station', 'Wi-Fi'],
  categories: ['lounge bar'],
  bookings: [],
  tables: { tableType2: 6, tableType4: 4 },
  location: { lat: 49.8333899, lng: 24.0138888 },
  name: 'ALLin lounge',
  rating: 4.7,
  address: '20/8 General Chuprynka`s Str., Lviv, Ukraine',
  phones: ['+38 (073) 078-88-03'],
  web: 'https://www.facebook.com/all.in.lviv',
  logoImg: 'assets/img/logo/48.jpg',
  profileImg: 'assets/img/profile/48.jpg'
},
{
  cuisines: ['Author\'s', 'European', 'Japanese', 'Ukrainian'],
  features: ['24h', 'hookah', 'karaoke', 'Wi-Fi'],
  categories: ['lounge bar'],
  bookings: [],
  location: { lat: 49.8392668, lng: 24.0286412 },
  tables: { tableType2: 6, tableType4: 4 },
  name: 'Club Split Lviv',
  rating: 4.3,
  address: '6/7 Adam Mitskevich Str., Lviv, Ukraine',
  phones: ['+38 (032) 242-22-00'],
  web: 'http://www.split.lviv.ua',
  logoImg: 'assets/img/logo/49.jpg',
  profileImg: 'assets/img/profile/49.jpg'
},
{
  cuisines: ['Author\'s', 'European', 'Vegetarian'],
  features: ['24h', 'karaoke', 'live music', 'non-smoking area', 'parking', 'summer terrace', 'Wi-Fi'],
  categories: ['lounge bar'],
  bookings: [],
  tables: { tableType2: 6, tableType4: 4 },
  location: { lat: 49.8410989, lng: 24.0291291 },
  name: 'Fashion Club',
  rating: 3.8,
  address: '1 Ivan Pidkova Sqr., Lviv, Ukraine',
  phones: ['+38 (032) 235-87-06', '+38 (067) 374-44-91'],
  web: 'http://fashion-club.in',
  logoImg: 'assets/img/logo/50.jpg',
  profileImg: 'assets/img/profile/50.jpg'
}
];
